# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "vmd" "nvme" "uas" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  service.btrfsAutoSnapshot = {
    enable = true;
    device = "/dev/disk/by-uuid/5b68ea29-4079-4d6c-a3f0-d95c67bae2bc";
  };

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/5b68ea29-4079-4d6c-a3f0-d95c67bae2bc";
      fsType = "btrfs";
      options = [ "subvol=@,compress=zstd,ssd,space_cache=v2,discard=async,noatime" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/5b68ea29-4079-4d6c-a3f0-d95c67bae2bc";
      fsType = "btrfs";
      options = [ "subvol=@home,compress=zstd,ssd,space_cache=v2,discard=async,noatime" ];
    };

  fileSystems."/var/log" =
    { device = "/dev/disk/by-uuid/5b68ea29-4079-4d6c-a3f0-d95c67bae2bc";
      fsType = "btrfs";
      options = [ "subvol=@var_log,compress=zstd,ssd,space_cache=v2,discard=async,noatime" ];
    };

  fileSystems."/var/cache" =
    { device = "/dev/disk/by-uuid/5b68ea29-4079-4d6c-a3f0-d95c67bae2bc";
      fsType = "btrfs";
      options = [ "subvol=@var_cache,compress=zstd,ssd,space_cache=v2,discard=async,noatime" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/7D16-5AFB";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/5e8baf23-46e0-493f-a65d-3ae6d0954de0"; }
    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp3s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp5s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;

  hardware.bluetooth.enable = true;
}
